# Generated by Django 4.0.6 on 2022-08-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='categoriya',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='value',
        ),
        migrations.RemoveField(
            model_name='portfolio_images',
            name='categoriya',
        ),
        migrations.RemoveField(
            model_name='portfolio_images',
            name='value',
        ),
        migrations.AddField(
            model_name='portfolio_images',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio_images',
            name='project_name',
            field=models.CharField(max_length=250),
        ),
    ]
